language: node_js
node_js:
  - "0.12"
before_install:
  - npm install -g bower
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
       npm install -g firebase-tools
    fi
after_success:
  - gulp build
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
       firebase deploy --token "$FIREBASE_TOKEN"
    fi

