language: node_js
node_js:
- '0.12'
before_install:
- openssl aes-256-cbc -K $encrypted_eecc6a0700f0_key -iv $encrypted_eecc6a0700f0_iv
  -in portal-b8ed1374e8de.json.enc -out portal-b8ed1374e8de.json -d
- npm install -g bower
test:
- gulp test
deploy:
  provider: gae
  keyfile: portal-b8ed1374e8de.json
  project: portal-143703
