language: node_js
node_js:
  - "0.12"
before_install:
  - npm install -g bower
  - npm install -g firebase-tools
after_success:
  - gulp build
  - firebase deploy --project brilliant-inferno-2901 --token "$FIREBASE_TOKEN"

