language: node_js
node_js:
  - '0.12'
before_install:
  - npm install -g bower
  - npm install -g npm # Force using the latest npm to get dedupe during install
install:
  - npm install --ignore-scripts
  - bower install

before_script:
  - npm run lint
  - if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      export IS_PUSH_TO_MASTER=true;
    fi
  - if [ $IS_PUSH_TO_MASTER ]; then
      - openssl aes-256-cbc -K $encrypted_eecc6a0700f0_key -iv $encrypted_eecc6a0700f0_iv -in portal-b8ed1374e8de.json.enc -out portal-b8ed1374e8de.json -d
      export GCLOUD_KEY="$(pwd)/portal-b8ed1374e8de.json";
    fi
sudo: false
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: "${GCLOUD_KEY}"
  project: portal-143703
