language: node_js
node_js:
  - '0.12'
before_install:
  - npm install -g bower
  - npm install -g npm # Force using the latest npm to get dedupe during install
install:
  - npm install --ignore-scripts
  - bower install
before_script:
  - openssl aes-256-cbc -K $encrypted_eecc6a0700f0_key -iv $encrypted_eecc6a0700f0_iv -in portal-b8ed1374e8de.json.enc -out portal-b8ed1374e8de.json -d
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: portal-b8ed1374e8de.json
  project: portal-143703
sudo: false
