language: node_js
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
node_js:
  - '0.12'
before_install:
  - openssl aes-256-cbc -K $encrypted_eecc6a0700f0_key -iv $encrypted_eecc6a0700f0_iv -in portal-b8ed1374e8de.json.enc -out portal-b8ed1374e8de.json -d
  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
  - echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - sudo apt-get update && sudo apt-get install google-cloud-sdk
  - gcloud auth activate-service-account --key-file portal-b8ed1374e8de.json
  - gcloud projects list
  - npm install -g bower
  - npm install -g npm
  - npm install -g phantomjs
  - npm install -g node-gyp
install:
  - npm install
  - bower install
script:
  - gulp build
  - gulp styles
  - gulp bump
after_success:
  - echo $PACKAGE_VERSION
  - gcloud config set project portal-143703
  - gcloud app deploy -q
sudo: true
